name: metametro
channels:
  - conda-forge
  - nodefaults
dependencies:
  - python=3.12.14
  - setuptools=84.0.0
  - pytest=9.1.1
  - pytest-cov=7.1.0
  - numpy=2.5.3
  - pyyaml=6.0.3
  - matplotlib-base=3.10.9
variables:
  PYTHONPATH: src
